import { TastingRecord, WineType, Clarity, Body, Aroma } from './types';

export const sampleTastingRecords: TastingRecord[] = [
  {
    id: '1',
    tasterName: 'Juan Pérez',
    date: '2023-10-26T10:00:00.000Z',
    wineName: 'Reserva Real',
    winery: 'Bodega Ficticia',
    year: 2018,
    wineType: WineType.RED,
    region: 'Rioja, España',
    appearanceColor: 'Rojo rubí profundo',
    appearanceClarity: Clarity.CLEAR,
    aromaIntensity: 4,
    aromaNotes: [Aroma.FRUITY, Aroma.WOODY, Aroma.SPICY],
    flavorAcidity: 3,
    flavorTannins: 4,
    flavorBody: Body.FULL,
    finish: 5,
    overallRating: 5,
    notes: 'Color rubí profundo. Aromas a frutos rojos maduros, vainilla y un toque de cuero. En boca es equilibrado, con taninos suaves y un final largo y persistente. Excelente vino.',
  },
  {
    id: '2',
    tasterName: 'Ana Gómez',
    date: '2023-11-15T14:30:00.000Z',
    wineName: 'Brisa Marina',
    winery: 'Viñedos del Sol',
    year: 2022,
    wineType: WineType.WHITE,
    region: 'Rías Baixas, España',
    appearanceColor: 'Amarillo pálido verdoso',
    appearanceClarity: Clarity.CLEAR,
    aromaIntensity: 5,
    aromaNotes: [Aroma.FRUITY, Aroma.FLORAL],
    flavorAcidity: 5,
    flavorTannins: 1,
    flavorBody: Body.LIGHT,
    finish: 4,
    overallRating: 4,
    notes: 'Amarillo pálido con reflejos verdosos. Muy aromático, con notas cítricas y florales. Fresco y ligero en boca, con una acidez vibrante. Ideal para mariscos.',
  },
    {
    id: '3',
    tasterName: 'Juan Pérez',
    date: '2024-01-20T18:00:00.000Z',
    wineName: 'Flor de Verano',
    winery: 'Campos Rosados',
    year: 2023,
    wineType: WineType.ROSE,
    region: 'Provenza, Francia',
    appearanceColor: 'Rosa pálido',
    appearanceClarity: Clarity.CLEAR,
    aromaIntensity: 3,
    aromaNotes: [Aroma.FRUITY],
    flavorAcidity: 4,
    flavorTannins: 1,
    flavorBody: Body.LIGHT,
    finish: 3,
    overallRating: 4,
    notes: 'Color rosa pálido y brillante. Aromas a fresa y frambuesa. Muy refrescante y fácil de beber.',
  },
];

export const WINE_TYPES_OPTIONS = Object.values(WineType);
export const CLARITY_OPTIONS = Object.values(Clarity);
export const BODY_OPTIONS = Object.values(Body);
export const AROMA_OPTIONS = Object.values(Aroma);